In [2]:
import numpy as np

In [1]:
import pandas as pd

In [5]:
from io import StringIO, BytesIO

In [22]:
type(False)


bool

In [35]:
mystr = "HiDude"
# mystr=mystr.upper()

In [36]:
print(mystr.isalnum()) #check if all chars are only alphabets and numbers and not spaces
print(mystr.isalpha()) #check if all chars in the string are alphabetic
print(mystr.isdigit()) #test if it is digit
print(mystr.istitle()) #returns True if all words in a text start with a upper case letter, AND the rest of the word are lower case letters, otherwise False. Symbols and numbers are ignored.
print(mystr.isupper()) #test if string contains uppercase (all chars)
print(mystr.islower()) #test if string contains lowercase (all chars)
print(mystr.isspace()) #test if contains spaces
print(mystr.endswith('e'))
print(mystr.startswith('H'))

True
True
False
False
False
False
False
True
True


In [37]:
str1 = "HelloWorld"


In [38]:
mystr.isalpha() or str1.isdigit()

True

In [39]:
mylist = [1,'Maths',2,'Science']
print(len(mylist))

4


In [42]:
mylist.append(3)
mylist
mylist.append([4,'French'])

In [43]:
mylist.insert(5,'English')
mylist

[1, 'Maths', 2, 'Science', 3, 'English', 'English', 3, [4, 'French']]

In [44]:
mylist.extend([5,'tamil'])
mylist

[1,
 'Maths',
 2,
 'Science',
 3,
 'English',
 'English',
 3,
 [4, 'French'],
 5,
 'tamil']

In [45]:
num = [1,2,3,4,5]
print(sum(num))


15


In [46]:
num.append(1)
num.count(1)

2

In [48]:
print(num.index(1))
print(num.index(1,1,len(num)))


0
5


In [49]:
print(min(num))
print(max(num))

1
5


In [50]:
num*2

[1, 2, 3, 4, 5, 1, 1, 2, 3, 4, 5, 1]

In [1]:
set_var = {"AR","Ani","San"}
set_var

{'AR', 'Ani', 'San'}

In [2]:
set_var.add("Harish")
set_var

{'AR', 'Ani', 'Harish', 'San'}

In [3]:
set_var1 = {"AR","Ani","San","DSP"}
set_var1.difference(set_var)

{'DSP'}

In [4]:
set_var.difference(set_var1)

{'Harish'}

In [5]:
set_var.difference_update(set_var1)

In [6]:
set_var

{'Harish'}

In [7]:
set_var.add("AR")

In [8]:
set_var.intersection(set_var1)

{'AR'}

In [9]:
my_dict={"Name":"Pricilla","role":"SD","office":"BDC"}
my_dict['role']

'SD'

In [10]:
for x in my_dict:
    print(x)

Name
role
office


In [11]:
for x in my_dict.values():
    print(x)

Pricilla
SD
BDC


In [12]:
for x in my_dict.items():
    print(x)

('Name', 'Pricilla')
('role', 'SD')
('office', 'BDC')


In [13]:
my_dict['pro']='Eiva'
my_dict

{'Name': 'Pricilla', 'role': 'SD', 'office': 'BDC', 'pro': 'Eiva'}

In [14]:
my_dict['Name']='Bby'
my_dict

{'Name': 'Bby', 'role': 'SD', 'office': 'BDC', 'pro': 'Eiva'}

In [15]:
muse1={'AR':'Nallai'}
muse2={'Ani':'kannana'}
museD={'classic':muse1,'rom':muse2}
museD

{'classic': {'AR': 'Nallai'}, 'rom': {'Ani': 'kannana'}}

In [16]:
museD['classic']['AR']

'Nallai'

In [17]:
my_tuple=("Prici","Judu","Jo")
my_tuple

('Prici', 'Judu', 'Jo')

In [18]:
my_tuple[0]
# we can't change individual value 
# but we can replace the whole tuple value

'Prici'

In [ ]:
# Numpy brush up

In [2]:
l1 = [1,2,3,4,5]
arr = np.array(l1)
type(arr)

numpy.ndarray

In [3]:
arr.shape

(5,)

In [4]:
l2 = [2,3,4,5,6]
l3 = [3,4,5,6,7]
arr = np.array([l1,l2,l3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [6]:
arr.shape

(3, 5)

In [8]:
arr.reshape(5,3)


array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [9]:
arr.shape

(3, 5)

In [10]:
arr[2][3]

6

In [11]:
arr[1:,2:]

array([[4, 5, 6],
       [5, 6, 7]])

In [12]:
arr[0:2,1:3]

array([[2, 3],
       [3, 4]])

In [14]:
arr1 = np.arange(0,10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr1 = np.arange(0,10,step=2)
arr1

array([0, 2, 4, 6, 8])

In [17]:
np.linspace(1,10,50) #divide into 50 equal points btw 1 and 10

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [21]:
arr2 = np.array([1,2,3,4,5])
arr3 = arr2.copy()
arr3[3:]=100
print(arr2)
arr3

[1 2 3 4 5]


array([  1,   2,   3, 100, 100])

In [22]:
val =3
arr2<val

array([ True,  True, False, False, False])

In [23]:
arr2*2

array([ 2,  4,  6,  8, 10])

In [25]:
arr2[arr2<8]

array([1, 2, 3, 4, 5])

In [26]:
np.ones(4)

array([1., 1., 1., 1.])

In [27]:
np.ones((2,4),dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [28]:
np.random.rand(2,3)

array([[0.04417121, 0.86268714, 0.36989361],
       [0.09481801, 0.23677514, 0.23306861]])

In [31]:
arr_exp=np.random.randn(4,4) #std normal dist

In [4]:
df = pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=['Column1','Column2','Column3','Column4'])

In [5]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [6]:
df.loc['Row1']

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int64

In [16]:
df['Column2']

Row1     1
Row2     5
Row3     9
Row4    13
Row5    17
Name: Column2, dtype: int64

In [8]:
 df.iloc[:,:]

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [9]:
df.iloc[:,1:]

Column2  Column3  Column4
Row1        1        2        3
Row2        5        6        7
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [12]:
df.iloc[0:2,0]

Row1    0
Row2    4
Name: Column1, dtype: int64

In [13]:
#convert dataframes into array
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [14]:
df['Column1'].value_counts()

12    1
4     1
16    1
8     1
0     1
Name: Column1, dtype: int64

In [15]:
#to check the null values
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [17]:
df[['Column1','Column2']]

Column1  Column2
Row1        0        1
Row2        4        5
Row3        8        9
Row4       12       13
Row5       16       17

In [2]:
df=pd.read_csv('covid_19_data.csv')
df.head()

SNo ObservationDate Province/State  Country/Region      Last Update  \
0    1      01/22/2020          Anhui  Mainland China  1/22/2020 17:00   
1    2      01/22/2020        Beijing  Mainland China  1/22/2020 17:00   
2    3      01/22/2020      Chongqing  Mainland China  1/22/2020 17:00   
3    4      01/22/2020         Fujian  Mainland China  1/22/2020 17:00   
4    5      01/22/2020          Gansu  Mainland China  1/22/2020 17:00   

   Confirmed  Deaths  Recovered  
0        1.0     0.0        0.0  
1       14.0     0.0        0.0  
2        6.0     0.0        0.0  
3        1.0     0.0        0.0  
4        0.0     0.0        0.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23481 entries, 0 to 23480
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   SNo              23481 non-null  int64  
 1   ObservationDate  23481 non-null  object 
 2   Province/State   11286 non-null  object 
 3   Country/Region   23481 non-null  object 
 4   Last Update      23481 non-null  object 
 5   Confirmed        23481 non-null  float64
 6   Deaths           23481 non-null  float64
 7   Recovered        23481 non-null  float64
dtypes: float64(3), int64(1), object(4)
memory usage: 1.4+ MB


In [4]:
df.describe()

SNo      Confirmed       Deaths      Recovered
count  23481.000000   23481.000000  23481.00000   23481.000000
mean   11741.000000    4735.580171    307.44338    1353.185214
std     6778.525171   20883.055308   1999.48770    9162.980596
min        1.000000       0.000000      0.00000       0.000000
25%     5871.000000      14.000000      0.00000       0.000000
50%    11741.000000     147.000000      2.00000       4.000000
75%    17611.000000    1022.000000     18.00000     132.000000
max    23481.000000  335395.000000  31855.00000  216169.000000

In [5]:
#get the unique categry counts
# df['XD'].value_counts()

df[df['Confirmed']>1022]

SNo ObservationDate Province/State  Country/Region  \
169      170      01/26/2020          Hubei  Mainland China   
216      217      01/27/2020          Hubei  Mainland China   
267      268      01/28/2020          Hubei  Mainland China   
319      320      01/29/2020          Hubei  Mainland China   
373      374      01/30/2020          Hubei  Mainland China   
...      ...             ...            ...             ...   
23471  23472      05/10/2020       Virginia              US   
23472  23473      05/10/2020     Washington              US   
23473  23474      05/10/2020  West Virginia              US   
23475  23476      05/10/2020      Wisconsin              US   
23480  23481      05/10/2020       Zhejiang  Mainland China   

               Last Update  Confirmed  Deaths  Recovered  
169          1/26/20 16:00     1058.0    52.0       42.0  
216          1/27/20 23:59     1423.0    76.0       45.0  
267          1/28/20 23:00     3554.0   125.0       80.0  
319          1/29/20 19:30     3554.0   125.0       88.0  
373          1/30/20 16:00     4903.0   162.0       90.0  
...                    ...        ...     ...        ...  
23471  2020-05-11 02:32:30    24081.0   839.0        0.0  
23472  2020-05-11 02:32:30    16891.0   931.0        0.0  
23473  2020-05-11 02:32:30     1360.0    54.0        0.0  
23475  2020-05-11 02:32:30    10219.0   400.0        0.0  
23480  2020-05-11 02:32:30     1268.0     1.0     1267.0  

[5869 rows x 8 columns]

In [2]:
data = ('col1,col2,col3\n'
           'x,y,1\n'
           'a,b,2\n'
           'c,d,3')

In [3]:
type(data)

str

In [6]:
pd.read_csv(StringIO(data))

col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [10]:
#Read from specific columns
df=pd.read_csv(StringIO(data),usecols=['col1','col3'])
            

In [11]:
df.to_csv('test.csv')

In [12]:
#specifying columns data types
data = ('a,b,c,d\n'
       '1,2,3,4\n'
       '5,6,7,8\n'
       '9,10,11')
print(data)

a,b,c,d
1,2,3,4
5,6,7,8
9,10,11


In [13]:
df=pd.read_csv(StringIO(data),dtype=object)

In [14]:
df

a   b   c    d
0  1   2   3    4
1  5   6   7    8
2  9  10  11  NaN

In [15]:
df['a'][1]

'5'

In [16]:
do = ('a,b,c,d\n'
       '1,2,3,4\n'
       '5,6,7,8\n'
       '9,10,11,12')

In [17]:
df1=pd.read_csv(StringIO(do),dtype=int)

In [18]:
df1

a   b   c   d
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [19]:
df1['a'][1]

5

In [20]:
#check the dtypes
df1.dtypes

a    int64
b    int64
c    int64
d    int64
dtype: object

In [23]:
df2=pd.read_csv(StringIO(do),dtype={'b':int,'c':np.float,'a':'Int64'})

In [24]:
df2

a   b     c   d
0  1   2   3.0   4
1  5   6   7.0   8
2  9  10  11.0  12

In [25]:
df2.dtypes

a      Int64
b      int64
c    float64
d      int64
dtype: object

In [8]:
dot = ('index,a,b,c\n'
            '4,apple,bat,5.7\n'
             '8,orange,cow,10')

In [10]:
pd.read_csv(StringIO(dot),index_col=0)

a    b     c
index                   
4       apple  bat   5.7
8      orange  cow  10.0

In [11]:
dots = ('a,b,c\n'
            '4,apple,bat\n'
             '8,orange,cow')

In [12]:
pd.read_csv(StringIO(dots),index_col=False)

a       b    c
0  4   apple  bat
1  8  orange  cow

In [14]:
pd.read_csv(StringIO(dots),usecols=['b','c'],index_col=False)

b    c
0   apple  bat
1  orange  cow

In [15]:
## Quoting and escape characters .(useful in NLP)
di ='a,b\n"hello,\\"Bob\\",niceto see you",5'

In [17]:
pd.read_csv(StringIO(di),escapechar='\\')

a  b
0  hello,"Bob",niceto see you  5